export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST';
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_GET_OTP_REQUEST = 'USER_GET_OTP_REQUEST';
export const USER_GET_OTP_REQUEST_SUCCESS = 'USER_GET_OTP_REQUEST_SUCCESS';
export const USER_GET_OTP_REQUEST_FAIL = 'USER_GET_OTP_REQUEST_FAIL';
export const USER_SIGNUP_SIGNIN_ERROR = 'USER_SIGNUP_SIGNIN_ERROR';
export const OPEN_CLOSE_SIDE_BAR_MENU = 'OPEN_CLOSE_SIDE_BAR_MENUR';
