export const USER_SESSION_REQUEST = 'USER_SESSION_REQUEST';
export const USER_SESSION_SUCCESS = 'USER_SESSION_SUCCESS';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_GET_OTP_REQUEST = 'USER_GET_OTP_REQUEST';
export const USER_GET_OTP_REQUEST_SUCCESS = 'USER_GET_OTP_REQUEST_SUCCESS';

export const BET_ACTIVE_USER_REQUEST = 'BET_ACTIVE_USER_REQUEST';
export const BET_ACTIVE_USER_SUCCESS = 'BET_ACTIVE_USER_SUCCESS';

export const BET_GAME_SESSION_REQUEST = 'BET_GAME_SESSION_REQUEST';
export const BET_GAME_SESSION_SUCCESS = 'BET_GAME_SESSION_SUCCESS';

export const GET_GAME_LAST_RESULT_REQUEST = 'GET_GAME_LAST_RESULT_REQUEST';
export const GET_GAME_LAST_RESULT_SUCCESS = 'GET_GAME_LAST_RESULT_SUCCESS';

export const USER_GET_OTP_REQUEST_FAIL = 'USER_GET_OTP_REQUEST_FAIL';
export const USER_SIGNUP_SIGNIN_ERROR = 'USER_SIGNUP_SIGNIN_ERROR';
export const CHANGE_USER_AVATAR_MODAL = 'CHANGE_USER_AVATAR_MODAL';
export const USER_WALLET_AND_GAME_BALANCE_REQUEST = 'USER_WALLET_AND_GAME_BALANCE_REQUEST';
export const USER_WALLET_AND_GAME_BALANCE_SUCCESS = 'USER_WALLET_AND_GAME_BALANCE_SUCCESS';

export const USER_BET_PREDICTION_HISTORY_REQUEST = 'USER_BET_PREDICTION_HISTORY_REQUEST';
export const USER_BET_PREDICTION_HISTORY_SUCCESS = 'USER_BET_PREDICTION_HISTORY_SUCCESS';

export const NEAREST_GAME_SESSION_AND_ACTIVE_SESSION_REQUEST = 'NEAREST_GAME_SESSION_AND_ACTIVE_SESSION_REQUEST';
export const NEAREST_GAME_SESSION_AND_ACTIVE_SESSION_SUCCESS = 'NEAREST_GAME_SESSION_AND_ACTIVE_SESSION_SUCCESS';

export const PASSCODE_REQUEST_BY_SUB_ADMIN_REQUEST = 'PASSCODE_REQUEST_BY_SUB_ADMIN_REQUEST';
export const PASSCODE_REQUEST_BY_SUB_ADMIN_SUCCESS = 'PASSCODE_REQUEST_BY_SUB_ADMIN_SUCCESS';

export const USER_WITHDRAWAL_AMOUNT_HISTORY_REQUEST = 'USER_WITHDRAWAL_AMOUNT_HISTORY_REQUEST';
export const USER_WITHDRAWAL_AMOUNT_HISTORY_SUCCESS = 'USER_WITHDRAWAL_AMOUNT_HISTORY_SUCCESS';

export const USER_DEPOSIT_AMOUNT_HISTORY_REQUEST = 'USER_DEPOSIT_AMOUNT_HISTORY_REQUEST';
export const USER_DEPOSIT_AMOUNT_HISTORY_SUCCESS = 'USER_DEPOSIT_AMOUNT_HISTORY_SUCCESS';

export const ADMIN_GAME_RESULT_LIST_REQUEST = 'ADMIN_GAME_RESULT_LIST_REQUEST';
export const ADMIN_GAME_RESULT_LIST_SUCCESS = 'ADMIN_GAME_RESULT_LIST_SUCCESS';

export const ALL_USERS_UNDER_SUB_ADMIN_LIST_REQUEST = 'ALL_USERS_UNDER_SUB_ADMIN_LIST_REQUEST';
export const ALL_USERS_UNDER_SUB_ADMIN_LIST_SUCCESS = 'ALL_USERS_UNDER_SUB_ADMIN_LIST_SUCCESS';

export const ALL_USERS_NORMAL_AND_SUB_ADMIN_LIST_REQUEST = 'ALL_USERS_NORMAL_AND_SUB_ADMIN_LIST_REQUEST';
export const ALL_USERS_NORMAL_AND_SUB_ADMIN_LIST_SUCCESS = 'ALL_USERS_NORMAL_AND_SUB_ADMIN_LIST_SUCCESS';

export const PENDING_WITHDRAWAL_REQUEST_LIST_REQUEST = 'PENDING_WITHDRAWAL_REQUEST_LIST_REQUEST';
export const PENDING_WITHDRAWAL_REQUEST_LIST_SUCCESS = 'PENDING_WITHDRAWAL_REQUEST_LIST_SUCCESS';

export const PENDING_DEPOSIT_REQUEST_LIST_REQUEST = 'PENDING_DEPOSIT_REQUEST_LIST_REQUEST';
export const PENDING_DEPOSIT_REQUEST_LIST_SUCCESS = 'PENDING_DEPOSIT_REQUEST_LIST_SUCCESS';

export const GENERATED_PASSCODE_LIST_BY_ADMIN_REQUEST = 'GENERATED_PASSCODE_LIST_BY_ADMIN_REQUEST';
export const GENERATED_PASSCODE_LIST_BY_ADMIN_SUCCESS = 'GENERATED_PASSCODE_LIST_BY_ADMIN_SUCCESS';


export const USER_BET_PREDICTION_STATUS_LOADING_REQUEST = 'USER_BET_PREDICTION_STATUS_LOADING_REQUEST';
export const USER_BET_PREDICTION_STATUS_EXPIRED = 'USER_BET_PREDICTION_STATUS_EXPIRED';
export const USER_BET_PREDICTION_STATUS_WAITING = 'USER_BET_PREDICTION_STATUS_WAITING';
export const USER_BET_PREDICTION_STATUS_READY = 'USER_BET_PREDICTION_STATUS_READY';
export const USER_BET_PREDICTION_STATUS = 'USER_BET_PREDICTION_STATUS';
export const USER_BET_PREDICTION_STATUS_READY_TIMER = 'USER_BET_PREDICTION_STATUS_READY_TIMER';
export const USER_BET_PREDICTION_STATUS_TIMER = 'USER_BET_PREDICTION_STATUS_TIMER';
export const USER_GAME_HISTORY_REQUEST = 'USER_GAME_HISTORY_REQUEST';
export const USER_GAME_HISTORY_SUCCESS = 'USER_GAME_HISTORY_SUCCESS';
export const USER_MONEY_TRANSACTIONS_REQUEST = 'USER_MONEY_TRANSACTIONS_REQUEST';
export const USER_MONEY_TRANSACTIONS_SUCCESS = 'USER_MONEY_TRANSACTIONS_SUCCESS';
